### ISSUE TITLE
Changes to scores from actionability.

### ISSUE THREAD

**Issue by ronakypatel** [clingen-data-model/data-exchange-shared-json#10]
I would recommend the following score structure, feel free to change the property names with your broader vision.

```
{
  "Scores": 
  [
    {
      "Outcome": "Pancreatic cancer morbidity and/or mortality",
      "Severity": "2",
      "Likelihood": "2C",
        "Interventions": [
          {
            "Intervention": "Periodic pancreatic imaging",
            "Effectiveness": "1E",
            "Nature Of Intervention": "3",
            "Total": "8CE"
          },
          {
            "Intervention": "Smoking cessation and avoidance",
            "Effectiveness": "2B",
            "Nature Of Intervention": "3",
            "Total": "9CB"
          }
        ]
    }
  ]
}
```

**Comment by tnavatar** [comment]
I think this makes sense, but would be an alteration of the structure of the message, and probably also the way actionability is represented on the site (see https://search.clinicalgenome.org/kb/genes/HGNC:6769) for an example.
It *should* be improved in this way, since this more nearly matches the structure of the underlying interpretation.

If Scott's OK with this (you might have the best sense of whether the actionability group would be OK with a slight change on the site)., I say lets' go ahead with your suggested change Ronak.

(I'm having a hard time forcing myself not to model this more deeply right now. Going to wait until phase 2 for that)

**Comment by sgoehringer** [comment]
@ronakypatel I like this structure!  

@tnavatar We may not even need to change the organization on the page either, just change how we loop through the data to build the UI/UX.

**Comment by ronakypatel** [comment]
Guys, we need to finalize this, so we can push it ahead.

**Comment by sgoehringer** [comment]
I am 100% fine with your proposed structure.  I was going to update the schema.  @tnavatar any reason to disagree?

**Comment by tnavatar** [comment]
Nope, happy to move forward on this.

**Comment by sgoehringer** [comment]
Closing - https://github.com/clingen-data-model/data-exchange-shared-json/commit/b3f75a7649691f7cd69258ab335151ed46b4c7f4
