### ISSUE TITLE
Content of the 'title' property

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#11]
> "title": "NHP2 Dyskeratosis Congenita"

https://github.com/clingen-data-model/data-exchange-shared-json/blob/87fa6290e08a78d16eb022a487a1c8254dd1603e/json-structure-phase1/Gene%20Curation%20Interface/gci.json#L6

@sgoehringer,

This looks like a concatenation of HGNC gene symbol and disease term. Is it correct?

**Comment by sgoehringer** [comment]
@jimmyzhen That is how it has been constructed to date.  Since some of the curations had multiple conditions with different names we allowed curators to generate their own title to allow them the control.  Do you have a concept of a human readable title or label of a curation in the DB? No it totally fine, I was just curious.  If not, as you said, if could be the concatenation of the HGNC and disease (I guess the preferred one if multiple).

**Comment by selinad** [comment]
Hi @sgoehringer -- what do you mean by "since some of the curations had multiple conditions with different names we allowed curators to generate their own tittle..." -- does this mean the titles don't always match the disease term?  

We create titles for display by concatenating the HGNC symbol with the disease term text, but I believe we don't store it as a "title" ( @jimmyzhen can confirm)

**Comment by sgoehringer** [comment]
Simply that diseases names for the conditions may be different (if you have more than one) and I wasn’t sure if the curators would want/could to choose a preferred condition to use as the condition name… maybe you simply prioritize one of them if multiple are provided.  

OrphaNet: 91387 	= Familial thoracic aortic aneurysm and aortic dissection
OMIM:102620 	= AORTIC ANEURYSM, FAMILIAL THORACIC 6; AAT6

Scott

**Comment by selinad** [comment]
thx @sgoehringer.  We have only one disease associated with the record and it is a disease term from MonDO (OMIM, DO, Orphanet, or NCIt allowed).  We do allow OMIM associations, but that is not the gene:disease record condition.

**Comment by sgoehringer** [comment]
@jimmyzhen Would it be possible to concatenating the HGNC symbol and the one disease term?

@selinad  This connected a few dots I didn't 100% appreciate.  Thank for clarifying! (-:  Thinking down the line a little, does that mean the website should display the equivalents set in the ontology or just display what the curator has selected?

**Comment by selinad** [comment]
@sgoehringer that's a good question!  We may need to talk through that one as it seems like it is related to the search as well -- it's possible the equivalence set could change....

**Comment by sgoehringer** [comment]
@selinad Yes, I agree... we have the 'knowledge' to consider making connections but should we and is it what curators are expecting?  And, to your point... the equivalence can change/evolve over time.  This could a fun discussion for the CSA (not this week) and provide some examples (if we can find them or make some up if needed) to illustrate the how it works.  Thoughts?  Glad to run with it if you like.

**Comment by selinad** [comment]
Hi @sgoehringer -- do you mean consider making connections but should we and is it what **stakeholders** are expecting?  The curators pick the term knowing the equivalence set at the time.  I'm not sure how the equivalence sets stay up to date wrt the search.  Do you want to give me an example of what you mean for the CSA discussion -- always love new ideas and someone who will run with them :-)!

**Comment by sgoehringer** [comment]
The equivalents data would be based from MONDO.  If we do this... I guess we just want to illustrate to the CSA and curators that if they choose OMIM1234 when curating, this curation will be displayed if a search for DOID321 is processed because an equivalence was provided by the ontology... and this equivalence could dynamically change so next week ORPHA987 match as well.  I would need to think about it some more... I think it is really cool concept.

**Comment by sgoehringer** [comment]
@jimmyzhen I just wanted to circle back to your original question.  Yes, "concatenation of HGNC gene symbol and disease term"  Does this work?

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
