### ISSUE TITLE
Defining = "tally" and "value"

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#13]
> "tally": "0.5"

https://github.com/clingen-data-model/data-exchange-shared-json/blob/87fa6290e08a78d16eb022a487a1c8254dd1603e/json-structure-phase1/Gene%20Curation%20Interface/gci.json#L56

@sgoehringer what does this value represent?  Is it the default score?

Also, is "value" the score the curator gave it?

thx!

**Comment by sgoehringer** [comment]
@jimmyzhen Correct, the value is what the curator assigned (ie, Variant is de novo = 14).  But since the guidelines state the the max score for Variant is de novo is 12 the tally would be sent as 12. IF the Variant is de novo was curated as 6 the tally would be sent as 6 because it is less than the max score.  This is also helpful in the areas where two values need to be add into a single tally (with a max) such as the Autosomal Recessive Disease section.  

Does this help?

**Comment by jimmyzhen** [comment]
@sgoehringer It sounds like the **value** is the combined score of the same variant type and the **tally** is a computed value based on whether the combined score is less or greater than the max score.

**Comment by sgoehringer** [comment]
@jimmyzhen That sounds right!  Do you plan on sharing both values?

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
